const ADJECTIVES = [
  "Abundant",
  "Acidic",
  "Acrobatic",
  "Adventurous",
  "Affectionate",
  "Agile",
  "Alert",
  "Altruistic",
  "Ambitious",
  "Amiable",
  "Ample",
  "Ancient",
  "Angry",
  "Annoyed",
  "Anxious",
  "Apprehensive",
  "Artistic",
  "Ashamed",
  "Astonishing",
  "Athletic",
  "Attentive",
  "Attractive",
  "Average",
  "Awkward",
  "Beautiful",
  "Beeg",
  "Benevolent",
  "Bewildered",
  "Big",
  "Bitter",
  "Blissful",
  "Boisterous",
  "Bold",
  "Bountiful",
  "Brave",
  "Bright",
  "Brilliant",
  "Busy",
  "Calm",
  "Capable",
  "Careful",
  "Careless",
  "Cautious",
  "Charming",
  "Cheerful",
  "Chilly",
  "Clumsy",
  "Cold",
  "Colossal",
  "Comfortable",
  "Comical",
  "Compassionate",
  "Competent",
  "Confident",
  "Confused",
  "Considerate",
  "Content",
  "Cooperative",
  "Courageous",
  "Cowardly",
  "Crazed",
  "Crazy",
  "Creamy",
  "Creative",
  "Creepy",
  "Cruel",
  "Curious",
  "Dainty",
  "Dangerous",
  "Daring",
  "Dark",
  "Dazzling",
  "Dead",
  "Deafening",
  "Decisive",
  "Deep",
  "Defiant",
  "Delicate",
  "Delightful",
  "Depressed",
  "Determined",
  "Devoted",
  "Dirty",
  "Disgusted",
  "Distinct",
  "Dizzy",
  "Drab",
  "Dramatic",
  "Dull",
  "Eager",
  "Easygoing",
  "Eccentric",
  "Ecstatic",
  "Elated",
  "Elegant",
  "Embarrassed",
  "Enchanting",
  "Encouraging",
  "Energetic",
  "Enormous",
  "Enthusiastic",
  "Evil",
  "Exasperated",
  "Excellent",
  "Excitable",
  "Excited",
  "Exhausted",
  "Exhilarated",
  "Extraordinary",
  "Fair",
  "Faithful",
  "Fancy",
  "Fantastic",
  "Fearful",
  "Fierce",
  "Filthy",
  "Fine",
  "Flamboyant",
  "Flawless",
  "Flexible",
  "Fluffy",
  "Foolish",
  "Forceful",
  "Fragile",
  "Frail",
  "Frantic",
  "Freezing",
  "Friendly",
  "Frightened",
  "Frivolous",
  "Frothy",
  "Frustrated",
  "Funny",
  "Furious",
  "Gentle",
  "Giddy",
  "Gifted",
  "Gigantic",
  "Glad",
  "Gloomy",
  "Glorious",
  "Graceful",
  "Grateful",
  "Greedy",
  "Grieving",
  "Grumpy",
  "Handsome",
  "Happy",
  "Hardworking",
  "Harmful",
  "Harmonious",
  "Harsh",
  "Healthy",
  "Heartfelt",
  "Helpful",
  "Hesitant",
  "Honest",
  "Hopeful",
  "Horrified",
  "Hospitable",
  "Humble",
  "Humorous",
  "Hungry",
  "Hurried",
  "Hypnotic",
  "Idealistic",
  "Ignorant",
  "Ill",
  "Imaginative",
  "Impatient",
  "Impressive",
  "Inquisitive",
  "Insane",
  "Insecure",
  "Intelligent",
  "Intense",
  "Intimidating",
  "Intriguing",
  "Inventive",
  "Irresponsible",
  "Irritable",
  "Itchy",
  "Jolly",
  "Joyful",
  "Jubilant",
  "Jumpy",
  "Kind",
  "Lazy",
  "Lively",
  "Lonely",
  "Longing",
  "Loud",
  "Loving",
  "Lucky",
  "Lustrous",
  "Mad",
  "Magical",
  "Malicious",
  "Melancholic",
  "Mellow",
  "Meticulous",
  "Mighty",
  "Mischievous",
  "Miserable",
  "Misguided",
  "Modest",
  "Moody",
  "Motivated",
  "Mysterious",
  "Nasty",
  "Naughty",
  "Nervous",
  "Nice",
  "Obedient",
  "Obnoxious",
  "Optimistic",
  "Ordinary",
  "Outgoing",
  "Outrageous",
  "Overjoyed",
  "Painful",
  "Passionate",
  "Patient",
  "Peaceful",
  "Perfect",
  "Playful",
  "Pleasant",
  "Plucky",
  "Polite",
  "Powerful",
  "Precious",
  "Proud",
  "Puzzled",
  "Quaint",
  "Quick",
  "Quiet",
  "Quirky",
  "Radiant",
  "Rash",
  "Rebellious",
  "Reflective",
  "Relaxed",
  "Reliable",
  "Remarkable",
  "Repulsive",
  "Resilient",
  "Responsible",
  "Restless",
  "Rich",
  "Ridiculous",
  "Robust",
  "Rude",
  "Sad",
  "Salty",
  "Sassy",
  "Scared",
  "Scary",
  "Selfish",
  "Sensible",
  "Sensitive",
  "Serene",
  "Serious",
  "Shiny",
  "Shy",
  "Silly",
  "Sincere",
  "Skillful",
  "Sleek",
  "Sleepy",
  "Slimy",
  "Sloppy",
  "Slow",
  "Sly",
  "Smart",
  "Smelly",
  "Smiling",
  "Smol",
  "Smooth",
  "Sneaky",
  "Soft",
  "Solemn",
  "Solid",
  "Sorrowful",
  "Sparkling",
  "Spicy",
  "Spirited",
  "Splendid",
  "Spontaneous",
  "Squeaky",
  "Stable",
  "Stern",
  "Sticky",
  "Stinky",
  "Strange",
  "Strong",
  "Stubborn",
  "Sturdy",
  "Subtle",
  "Successful",
  "Sulky",
  "Sunny",
  "Surprised",
  "Suspicious",
  "Sweet",
  "Swift",
  "Sympathetic",
  "Tactful",
  "Talented",
  "Talkative",
  "Tasty",
  "Tenacious",
  "Tender",
  "Thankful",
  "Thoughtful",
  "Thrilled",
  "Timid",
  "Tired",
  "Tolerant",
  "Tough",
  "Tranquil",
  "Trusting",
  "Trustworthy",
  "Truthful",
  "Ugly",
  "Unbelievable",
  "Unbiased",
  "Uncomfortable",
  "Unconventional",
  "Understanding",
  "Unforgettable",
  "Unique",
  "Unpredictable",
  "Unusual",
  "Upbeat",
  "Uplifting",
  "Valiant",
  "Vibrant",
  "Victorious",
  "Vigilant",
  "Vivacious",
  "Wandering",
  "Warm",
  "Wary",
  "Weak",
  "Wealthy",
  "Weary",
  "Whimsical",
  "Wild",
  "Wise",
  "Witty",
  "Wonderful",
  "Worried",
  "Wretched",
  "Wrong",
  "Youthful",
  "Zealous",
];

const COLORS = [
  "Alabaster",
  "Alice Blue",
  "Alloy Orange",
  "Almond",
  "Amaranth",
  "Amber",
  "Amethyst",
  "Antique Brass",
  "Aqua",
  "Aquamarine",
  "Arctic Blue",
  "Army Green",
  "AshGray",
  "Auburn",
  "Azure",
  "BabyBlue",
  "BabyPink",
  "Banana Yellow",
  "Beige",
  "Berry",
  "Beryl Green",
  "Bistre",
  "Black",
  "Blanched Almond",
  "Blue",
  "Blue Gray",
  "Blue Green",
  "Blue Violet",
  "Blush Pink",
  "Brick Red",
  "Bright Green",
  "Bronze",
  "Brown",
  "Bubble Gum Pink",
  "Buff",
  "Burgundy",
  "Burnt Orange",
  "Burnt Sienna",
  "Burnt Umber",
  "Cadet Blue",
  "Canary Yellow",
  "Candy Pink",
  "Caramel",
  "Cardinal Red",
  "Caribbean Green",
  "Carmine",
  "Carolina Blue",
  "Celadon",
  "Celestial Blue",
  "Cerise",
  "Cerulean",
  "Champagne",
  "Chartreuse",
  "Cherry Blossom Pink",
  "Chestnut",
  "Chocolate Brown",
  "Cinnamon",
  "Citrine",
  "Citrus Orange",
  "Claret",
  "Cobalt Blue",
  "Coffee Brown",
  "Cool Gray",
  "Copper",
  "Coral",
  "Coral Pink",
  "Cornflower Blue",
  "Cornsilk",
  "Cream",
  "Crimson",
  "Cyan",
  "Dandelion Yellow",
  "Dark Blue",
  "Dark Brown",
  "Dark Cyan",
  "Dark Goldenrod",
  "Dark Gray",
  "Dark Green",
  "Dark Khaki",
  "Dark Magenta",
  "Dark Olive Green",
  "Dark Orange",
  "Dark Orchid",
  "Dark Red",
  "Dark Salmon",
  "Dark Sea Green",
  "Dark Slate Blue",
  "Dark Slate Gray",
  "Dark Turquoise",
  "Dark Violet",
  "Deep Pink",
  "Deep Sky Blue",
  "Denim Blue",
  "Desert Sand",
  "Dodger Blue",
  "Eggplant",
  "Electric Blue",
  "Electric Green",
  "Emerald Green",
  "Fern Green",
  "Firebrick",
  "Flamingo Pink",
  "Forest Green",
  "Fuchsia",
  "Fuzzy Wuzzy Brown",
  "Gainsboro",
  "Gamboge Orange",
  "Ghost White",
  "Ginger",
  "Glaucous Blue",
  "Gold",
  "Goldenrod",
  "Granny Smith Apple",
  "Grape Purple",
  "Grass Green",
  "Gray",
  "Green",
  "Green Yellow",
  "Honeydew",
  "Hot Pink",
  "Indian Red",
  "Indigo",
  "Ivory",
  "Jade Green",
  "Jasmine",
  "Jungle Green",
  "Khaki",
  "Lapis Lazuli Blue",
  "Lavender",
  "Lemon Yellow",
  "Light Cyan",
  "Light Goldenrod",
  "Light Gray",
  "Light Green",
  "Light Pink",
  "Light Salmon",
  "Light Sea Green",
  "Light Sky Blue",
  "Light Slate Gray",
  "Light Steel Blue",
  "Light Yellow",
  "Lilac",
  "Lime Green",
  "Lime Yellow",
  "Linen",
  "Magenta",
  "Mahogany",
  "Maize",
  "Malachite Green",
  "Mango",
  "Maroon",
  "Mauve",
  "Medium Aquamarine",
  "Medium Blue",
  "Medium Orchid",
  "Medium Purple",
  "Medium Sea Green",
  "Medium Slate Blue",
  "Medium Spring Green",
  "Medium Turquoise",
  "Medium Violet Red",
  "Midnight Blue",
  "Mint Cream",
  "Misty Rose",
  "Moccasin",
  "Moonstone Blue",
  "Moss Green",
  "Mountain Meadow Green",
  "Mustard Yellow",
  "Myrtle Green",
  "Navajo White",
  "Navy Blue",
  "Neon Green",
  "Ochre",
  "Old Gold",
  "Old Lace",
  "Olive",
  "Olive Drab",
  "Orange",
  "Orange Red",
  "Orchid",
  "Pale Aqua",
  "Pale Blue",
  "Pale Brown",
  "Pale Cyan",
  "Pale Goldenrod",
  "Pale Gray",
  "Pale Green",
  "Pale Pink",
  "Pale Plum",
  "Pale Turquoise",
  "Pale Violet",
  "Papaya Whip",
  "Pastel Blue",
  "Pastel Green",
  "Pastel Pink",
  "Peach",
  "Pear Green",
  "Periwinkle",
  "Persian Blue",
  "Pine Green",
  "Pink",
  "Pink Lavender",
  "Plum",
  "Powder Blue",
  "Pumpkin Orange",
  "Purple",
  "Red",
  "Rich Black",
  "Robin Egg Blue",
  "Rose",
  "Rose Gold",
  "Rose Pink",
  "Royal Blue",
  "Ruby Red",
  "Russet",
  "Rust Orange",
  "Saffron",
  "Salmon",
  "Sandy Brown",
  "Sap Green",
  "Sea Blue",
  "Sea Green",
  "Seashell",
  "Sepia",
  "Shadow Blue",
  "Shamrock Green",
  "Shocking Pink",
  "Sienna",
  "Silver",
  "Sky Blue",
  "Slate Blue",
  "Slate Gray",
  "Smoky Black",
  "Snow White",
  "Spring Green",
  "Steel Blue",
  "Sunflower Yellow",
  "Tan",
  "Tangerine",
  "Taupe",
  "Teal",
  "Thistle",
  "Tomato Red",
  "Topaz",
  "Turquoise",
  "Ultramarine Blue",
  "Umber",
  "Vanilla",
  "Vermilion",
  "Violet",
  "Viridian Green",
  "Warm Gray",
  "Wheat",
  "White",
  "White Smoke",
  "Wild Strawberry",
  "Willow Green",
  "Wisteria Purple",
  "Xanadu Green",
  "Yellow",
  "Yellow Green",
  "Yellow Orange",
  "Zaffre Blue",
];

const ANIMALS = [
  "Alligator",
  "Ant",
  "Anteater",
  "Antelope",
  "Armadillo",
  "Baboon",
  "Badger",
  "Barracuda",
  "Bat",
  "Beaver",
  "Bluejay",
  "Bob",
  "Bobbus",
  "Bub",
  "Buffalo",
  "Butterfly",
  "Camel",
  "Capybara",
  "Caterpillar",
  "Cheetah",
  "Chimpanzee",
  "Cobra",
  "Cockroach",
  "Crab",
  "Crocodile",
  "Dinosaur",
  "Dolphin",
  "Donkey",
  "Dragonfly",
  "Eagle",
  "Elephant",
  "Falcon",
  "Ferret",
  "Flamingo",
  "Frog",
  "Gazelle",
  "Giraffe",
  "Gorilla",
  "Grasshopper",
  "Hamster",
  "Hedgehog",
  "Hippopotamus",
  "Hummingbird",
  "Hyena",
  "Iguana",
  "Impala",
  "Jackal",
  "Jellyfish",
  "Kangaroo",
  "Koala",
  "Komodo",
  "Leopard",
  "Lion",
  "Lizard",
  "Llama",
  "Lobster",
  "Magpie",
  "Mantis",
  "Mongoose",
  "Monkey",
  "Moose",
  "Mosquito",
  "Narwhal",
  "Octopus",
  "Opossum",
  "Ostrich",
  "Otter",
  "Owl",
  "Panther",
  "Pelican",
  "Penguin",
  "Porcupine",
  "Puma",
  "Quail",
  "Rabbit",
  "Raccoon",
  "Rat",
  "Rhinoceros",
  "Salamander",
  "Scorpion",
  "Seahorse",
  "Seal",
  "Shark",
  "Sheep",
  "Skunk",
  "Sloth",
  "Snake",
  "Sparrow",
  "Squirrel",
  "Starfish",
  "Stingray",
  "Tiger",
  "Toucan",
  "Turkey",
  "Turtle",
  "Vulture",
  "Walrus",
  "Warthog",
  "Whale",
  "Wolf",
  "Wolverine",
  "Wombat",
  "Woodpecker",
  "Yak",
  "Zebra",
];

const CITY_DESCRIPTORS = [
  "Abodes",
  "Acreage",
  "Area",
  "Avenue",
  "Borough",
  "Boulevard",
  "Buildings",
  "Bungalow",
  "Burb",
  "Burbs",
  "Capital City",
  "Capital",
  "Castle",
  "Chateau",
  "Citadel",
  "City",
  "Cityscape",
  "Close",
  "Colony",
  "Commonwealth",
  "Community",
  "Conurbation",
  "Cosmopolis",
  "Cottage",
  "Country",
  "Countryside",
  "County",
  "Court",
  "Crescent",
  "District",
  "Domain",
  "Domicile",
  "Dominion",
  "Downtown",
  "Duchy",
  "Dwelling",
  "Empire",
  "Enclave",
  "Estate",
  "Farms",
  "Farmhouse",
  "Farmland",
  "Field",
  "Green",
  "Ground",
  "Grounds",
  "Habitat",
  "Hall",
  "Hamlet",
  "Holding",
  "Home",
  "Homestead",
  "Kingdom",
  "Land",
  "Landmark",
  "Landmass",
  "Landscape",
  "Lane",
  "Locale",
  "Locality",
  "Lot",
  "Manor",
  "Manor",
  "Mansion",
  "Meadow",
  "Meadowland",
  "Megacity",
  "Megalopol",
  "Megalopolis",
  "Megatropolis",
  "Metropolis",
  "Monarchy",
  "Municipality",
  "Nation",
  "Neighborhood",
  "Outback",
  "Palace",
  "Palatinate",
  "Parcel",
  "Park",
  "Parkland",
  "Pasture",
  "Plantation",
  "Plot",
  "Preserve",
  "Principality",
  "Property",
  "Province",
  "Quarter",
  "Ranch",
  "Realm",
  "Region",
  "Republic",
  "Reserve",
  "Residence",
  "Road",
  "Sector",
  "Settlement",
  "Shire",
  "Site",
  "Soil",
  "Sovereignty",
  "Square",
  "State",
  "Street",
  "Subdivision",
  "Suburb",
  "Suburbia",
  "Suzerain",
  "Terrain",
  "Territory",
  "Tower",
  "Town",
  "Townlet",
  "Township",
  "Tract",
  "Utopia",
  "Villa",
  "Village",
  "Wild",
  "Wilderness",
  "Zone",
];

const NOUNS = [
  "Alarm Clocks",
  "Apples",
  "Apricots",
  "Aprons",
  "Asparagus",
  "Avocados",
  "Backpacks",
  "Bacons",
  "Baking Trays",
  "Ballet Shoes",
  "Bananas",
  "Bandages",
  "Baseball Bats",
  "Basketballs",
  "Beach Towels",
  "Beds",
  "Beef",
  "Bell Peppers",
  "Bicycles",
  "Binoculars",
  "Birds",
  "Blackberries",
  "Blankets",
  "Blenders",
  "Blueberries",
  "Boats",
  "Books",
  "Bowls",
  "Breads",
  "Broccoli",
  "Brooms",
  "Buckets",
  "Burgers",
  "Burgers",
  "Burritos",
  "Butters",
  "Cabbages",
  "Cakes",
  "Cakes",
  "Calculators",
  "Calendars",
  "Cameras",
  "Camping Chairs",
  "Candles",
  "Carrots",
  "Cars",
  "Cars",
  "Cats",
  "Cauliflowers",
  "Celeries",
  "Cereals",
  "Chairs",
  "Cheeses",
  "Cherries",
  "Chess Pieces",
  "Chessboards",
  "Chicken",
  "Chili Peppers",
  "Chocolates",
  "Coconuts",
  "Coffee Machines",
  "Coffee Mugs",
  "Compasses",
  "Compost",
  "Conditioners",
  "Cookies",
  "Coolers",
  "Corn",
  "Cucumbers",
  "Cups",
  "Curries",
  "Cutting Boards",
  "Cycling Helmets",
  "Desks",
  "Dishwashers",
  "Dogs",
  "Dolphins",
  "Drumsticks",
  "Dumbbells",
  "Dustpans",
  "Eagles",
  "Eggplants",
  "Eggs",
  "Elephants",
  "Exercise Mats",
  "Figs",
  "Firewood",
  "First Aid Kits",
  "Fish",
  "Fishing Rods",
  "Flowers",
  "Flower Vases",
  "Football Cleats",
  "Football Helmets",
  "Forks",
  "Fried Chicken",
  "Garlic",
  "Giraffes",
  "Glasses",
  "Goggles",
  "Golf Clubs",
  "Grapes",
  "Green Beans",
  "Guacamole",
  "Guitar Picks",
  "Guitars",
  "Hairbrushes",
  "Hairdryers",
  "Hammers",
  "Hammocks",
  "Hams",
  "Harmonicas",
  "Headphones",
  "Honeys",
  "Houses",
  "Hummus",
  "Ice",
  "Ice Cream",
  "Insect Repellent",
  "Ironing Boards",
  "Irons",
  "Islands",
  "Jackets",
  "Jams",
  "Jeans",
  "Jump Ropes",
  "Jungles",
  "Kales",
  "Kangaroos",
  "Keychains",
  "Keys",
  "Kiwis",
  "Knives",
  "Lambs",
  "Lamps",
  "Laptop Bags",
  "Laptops",
  "Lasagnas",
  "Laundry Detergents",
  "Lemons",
  "Lettuces",
  "Life Jackets",
  "Limes",
  "Lions",
  "Makeup",
  "Mangos",
  "Maps",
  "Marshmallows",
  "Meatballs",
  "Medicines",
  "Microphones",
  "Microwaves",
  "Milk",
  "Mirrors",
  "Mixers",
  "Moons",
  "Mops",
  "Motorbikes",
  "Mountains",
  "Mushrooms",
  "Nail Polish",
  "Nests",
  "Ninjas",
  "Noodles",
  "Notebooks",
  "Oats",
  "Oceans",
  "Onions",
  "Oranges",
  "Oven Mitts",
  "Ovens",
  "Owls",
  "Paintings",
  "Pancakes",
  "Pans",
  "Papayas",
  "Passports",
  "Pastas",
  "Pastas",
  "Peaches",
  "Peanut Butter",
  "Pears",
  "Peas",
  "Pencils",
  "Penguins",
  "Pens",
  "Perfumes",
  "Pestos",
  "Phones",
  "Pianos",
  "Picnic Baskets",
  "Picture Frames",
  "Pillows",
  "Pineapples",
  "Pizzas",
  "Planes",
  "Plants",
  "Plates",
  "Plums",
  "Pomegranates",
  "Pork",
  "Potatoes",
  "Pots",
  "Printers",
  "Projectors",
  "Pumpkins",
  "Queens",
  "Quills",
  "Quinoa",
  "Radishes",
  "Raspberries",
  "Razors",
  "Refrigerators",
  "Remote Controls",
  "Rice",
  "Rivers",
  "Robots",
  "Roller Skates",
  "Running Shoes",
  "Sails",
  "Salads",
  "Salmon",
  "Salsas",
  "Sandwiches",
  "Sausages",
  "Saxophones",
  "Scales",
  "Scanners",
  "Sculptures",
  "Shampoos",
  "Sheet Music",
  "Shoes",
  "Shrimp",
  "Skateboards",
  "Sleeping Bags",
  "Snacks",
  "Soap Dispensers",
  "Soaps",
  "Soccer Balls",
  "Socks",
  "Soups",
  "Speakers",
  "Spinaches",
  "Spoons",
  "Squashes",
  "Staplers",
  "Stir Fries",
  "Strawberries",
  "Suitcases",
  "Sunglasses",
  "Suns",
  "Sunscreens",
  "Sushi",
  "Sushi",
  "Sweet Potatoes",
  "SwimCaps",
  "Swimsuits",
  "Tables",
  "Tacos",
  "Tape Dispensers",
  "Telescopes",
  "Tennis Rackets",
  "Tents",
  "Thermometers",
  "Tigers",
  "TissueBoxes",
  "Tomatoes",
  "Toothbrushes",
  "Toothpastes",
  "Towels",
  "Trains",
  "Trash",
  "Trash Cans",
  "Trees",
  "Trumpets",
  "TShirts",
  "Tuna",
  "Turkeys",
  "TVs",
  "Umbrellas",
  "Unicorns",
  "USB Drives",
  "Vacuum Cleaners",
  "VideoGames",
  "Violins",
  "Violins",
  "Volcanoes",
  "Volleyballs",
  "Waffles",
  "Wallets",
  "Watches",
  "Water Bottles",
  "Water",
  "Water Filters",
  "Watermelons",
  "Whales",
  "Whiteboards",
  "WineGlasses",
  "X-rays",
  "Xylophones",
  "Yachts",
  "YogaBlocks",
  "YogaMats",
  "Yogurts",
  "Zebras",
  "Zoos",
  "Zucchinis",
];

export function generateGameId() {
  const randomNumber = Math.floor(Math.random() * 100);
  const gameId =
    ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)] +
    COLORS[Math.floor(Math.random() * COLORS.length)] +
    (randomNumber % 2 == 0
      ? ANIMALS[Math.floor(Math.random() * ANIMALS.length)]
      : NOUNS[Math.floor(Math.random() * NOUNS.length)]);
  return gameId.replaceAll(" ", "");
}

export function generateCityName() {
  const randomNumber = Math.floor(Math.random() * 100);
  return (
    ADJECTIVES[Math.floor(Math.random() * ADJECTIVES.length)] +
    " " +
    CITY_DESCRIPTORS[Math.floor(Math.random() * CITY_DESCRIPTORS.length)] +
    " of " +
    (randomNumber % 2 == 0
      ? NOUNS[Math.floor(Math.random() * NOUNS.length)]
      : "the " + ANIMALS[Math.floor(Math.random() * ANIMALS.length)])
  );
}
